language: go

go:
  - tip
  - 1.8

install:
  - go get $(go list -f '{{join .Imports "\n"}}' ./... | sort | uniq | grep -v caddy-hugo) || true
  - go get github.com/mholt/caddy/caddyhttp

before_script:
  - ./before_script.sh
script:
  - go build caddy
