language: go

go:
  - tip
  - 1.8

install:
  - go get $(go list -f '{{join .Imports "\n"}}' ./... | sort | uniq | grep -v caddy-hugo) || true
  - go get github.com/mholt/caddy/caddyhttp

before_script:
  - mkdir $GOPATH/src/caddy
  - touch $GOPATH/src/caddy/main.go
  - echo 'package main
    import "github.com/mholt/caddy/caddy/caddymain"
    import "github.com/hacdias/caddy-hugo"
    func main() {
    caddymain.Run()
    }' >> $GOPATH/src/caddy/main.go

script:
  - go build caddy
