language: go

go:
  - tip

install:
  - go get -u -v $(go list -f '{{join .Imports "\n"}}' ./... | sort | uniq | grep -v filemanager)
  - go get -u -v github.com/mholt/caddy/caddyhttp
  - go get github.com/gordonklaus/ineffassign

script:
  - sed -i 's/\_ \"github.com\/mholt\/caddy\/caddyhttp\"/\_ \"github.com\/mholt\/caddy\/caddyhttp\"\n\_ \"github.com\/hacdias\/filemanager\/caddy\/filemanager\"/g' $GOPATH/src/github.com/mholt/caddy/caddy/caddymain/run.go
  - go build -o binary github.com/mholt/caddy/caddy
  - go build github.com/hacdias/filemanager
  - ineffassign .
