language: go

go:
  - tip

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

install:
  - go get -u -v $(go list -f '{{join .Imports "\n"}}' ./... | sort | uniq | grep -v filemanager)
  - go get -u -v github.com/mholt/caddy/caddyhttp
  - go get github.com/gordonklaus/ineffassign
  - go get github.com/mitchellh/gox
  - go get github.com/tcnksm/ghr

script:
  - ineffassign .
  - go test ./... -timeout 30s -tags
  - cd cmd/filemanager
  - mkdir dist
  - gox -output "dist/{{.OS}}-{{.Arch}}-{{.Dir}}"
  - ls dist/
  - ghr --username hacdias --token $GITHUB_TOKEN --replace --prerelease --debug latest dist/
