language: go

go:
- tip

install:
  - go get -u -v $(go list -f '{{join .Imports "\n"}}' ./... | sort | uniq | grep -v caddy-filemanager)
  - go get -u -v github.com/mholt/caddy/caddyhttp
  - go get -u -v github.com/caddyserver/caddydev
  - go install github.com/caddyserver/caddydev
  - go get github.com/gordonklaus/ineffassign

script:
  - diff <(echo -n) <(gofmt -s -d .)
  - sed -i 's/\_ \"github.com\/mholt\/caddy\/caddyhttp\"/\_ \"github.com\/mholt\/caddy\/caddyhttp\"\n\_ \"github.com\/hacdias\/caddy-filemanager\"/g' $GOPATH/src/github.com/mholt/caddy/caddy/caddymain/run.go
  - go build github.com/mholt/caddy/caddy
  - ineffassign .
